[workspace]
resolver = "2"
members = [
    # Core lib logic
    "life",

    # Runner for rpi pico
    "pico-life",

    # Runner for Desktop-esque environments
    "big-life",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
