[package]
name = "big-life"
version = "0.1.0"
edition = "2021"

[dependencies]
life = { path = "../life" }

minifb = "0.27"
rand = { version = "0.8", features = ["small_rng"], default-features = false }
